'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Data


<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ServiceModel.ServiceContractAttribute(ConfigurationName:="IService1")>  _
Public Interface IService1
    
    'CODEGEN: Parameter 'GetDataResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetData", ReplyAction:="http://tempuri.org/IService1/GetDataResponse"),  _
     System.ServiceModel.XmlSerializerFormatAttribute()>  _
    Function GetData(ByVal request As GetDataRequest) As GetDataResponse
    
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetData", ReplyAction:="http://tempuri.org/IService1/GetDataResponse")>  _
    Function GetDataAsync(ByVal request As GetDataRequest) As System.Threading.Tasks.Task(Of GetDataResponse)
    
    'CODEGEN: Parameter 'GetDataUsingDataContractResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction:="http://tempuri.org/IService1/GetDataUsingDataContractResponse"),  _
     System.ServiceModel.XmlSerializerFormatAttribute(),  _
     System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object()))>  _
    Function GetDataUsingDataContract(ByVal request As GetDataUsingDataContractRequest) As GetDataUsingDataContractResponse
    
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction:="http://tempuri.org/IService1/GetDataUsingDataContractResponse")>  _
    Function GetDataUsingDataContractAsync(ByVal request As GetDataUsingDataContractRequest) As System.Threading.Tasks.Task(Of GetDataUsingDataContractResponse)
    
    'CODEGEN: Parameter 'GetAHASRiskResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetAHASRisk", ReplyAction:="http://tempuri.org/IService1/GetAHASRiskResponse"),  _
     System.ServiceModel.XmlSerializerFormatAttribute(),  _
     System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object()))>  _
    Function GetAHASRisk(ByVal request As GetAHASRiskRequest) As GetAHASRiskResponse
    
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetAHASRisk", ReplyAction:="http://tempuri.org/IService1/GetAHASRiskResponse")>  _
    Function GetAHASRiskAsync(ByVal request As GetAHASRiskRequest) As System.Threading.Tasks.Task(Of GetAHASRiskResponse)
    
    'CODEGEN: Parameter 'GetAHASRisk12Result' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetAHASRisk12", ReplyAction:="http://tempuri.org/IService1/GetAHASRisk12Response"),  _
     System.ServiceModel.XmlSerializerFormatAttribute(),  _
     System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object()))>  _
    Function GetAHASRisk12(ByVal request As GetAHASRisk12Request) As GetAHASRisk12Response
    
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetAHASRisk12", ReplyAction:="http://tempuri.org/IService1/GetAHASRisk12Response")>  _
    Function GetAHASRisk12Async(ByVal request As GetAHASRisk12Request) As System.Threading.Tasks.Task(Of GetAHASRisk12Response)
    
    'CODEGEN: Parameter 'GetUNITRiskResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetUNITRisk", ReplyAction:="http://tempuri.org/IService1/GetUNITRiskResponse"),  _
     System.ServiceModel.XmlSerializerFormatAttribute(),  _
     System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object()))>  _
    Function GetUNITRisk(ByVal request As GetUNITRiskRequest) As GetUNITRiskResponse
    
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetUNITRisk", ReplyAction:="http://tempuri.org/IService1/GetUNITRiskResponse")>  _
    Function GetUNITRiskAsync(ByVal request As GetUNITRiskRequest) As System.Threading.Tasks.Task(Of GetUNITRiskResponse)
    
    'CODEGEN: Parameter 'GetUNITRisk12Result' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetUNITRisk12", ReplyAction:="http://tempuri.org/IService1/GetUNITRisk12Response"),  _
     System.ServiceModel.XmlSerializerFormatAttribute(),  _
     System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object()))>  _
    Function GetUNITRisk12(ByVal request As GetUNITRisk12Request) As GetUNITRisk12Response
    
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetUNITRisk12", ReplyAction:="http://tempuri.org/IService1/GetUNITRisk12Response")>  _
    Function GetUNITRisk12Async(ByVal request As GetUNITRisk12Request) As System.Threading.Tasks.Task(Of GetUNITRisk12Response)
    
    'CODEGEN: Parameter 'GetDAMSResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetDAMS", ReplyAction:="http://tempuri.org/IService1/GetDAMSResponse"),  _
     System.ServiceModel.XmlSerializerFormatAttribute(),  _
     System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object()))>  _
    Function GetDAMS(ByVal request As GetDAMSRequest) As GetDAMSResponse
    
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetDAMS", ReplyAction:="http://tempuri.org/IService1/GetDAMSResponse")>  _
    Function GetDAMSAsync(ByVal request As GetDAMSRequest) As System.Threading.Tasks.Task(Of GetDAMSResponse)
    
    'CODEGEN: Parameter 'GetLANDFILLSResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetLANDFILLS", ReplyAction:="http://tempuri.org/IService1/GetLANDFILLSResponse"),  _
     System.ServiceModel.XmlSerializerFormatAttribute(),  _
     System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object()))>  _
    Function GetLANDFILLS(ByVal request As GetLANDFILLSRequest) As GetLANDFILLSResponse
    
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetLANDFILLS", ReplyAction:="http://tempuri.org/IService1/GetLANDFILLSResponse")>  _
    Function GetLANDFILLSAsync(ByVal request As GetLANDFILLSRequest) As System.Threading.Tasks.Task(Of GetLANDFILLSResponse)
    
    'CODEGEN: Parameter 'GetGOLFResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetGOLF", ReplyAction:="http://tempuri.org/IService1/GetGOLFResponse"),  _
     System.ServiceModel.XmlSerializerFormatAttribute(),  _
     System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object()))>  _
    Function GetGOLF(ByVal request As GetGOLFRequest) As GetGOLFResponse
    
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetGOLF", ReplyAction:="http://tempuri.org/IService1/GetGOLFResponse")>  _
    Function GetGOLFAsync(ByVal request As GetGOLFRequest) As System.Threading.Tasks.Task(Of GetGOLFResponse)
    
    'CODEGEN: Parameter 'GetSTRIKESResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetSTRIKES", ReplyAction:="http://tempuri.org/IService1/GetSTRIKESResponse"),  _
     System.ServiceModel.XmlSerializerFormatAttribute(),  _
     System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object()))>  _
    Function GetSTRIKES(ByVal request As GetSTRIKESRequest) As GetSTRIKESResponse
    
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetSTRIKES", ReplyAction:="http://tempuri.org/IService1/GetSTRIKESResponse")>  _
    Function GetSTRIKESAsync(ByVal request As GetSTRIKESRequest) As System.Threading.Tasks.Task(Of GetSTRIKESResponse)
    
    'CODEGEN: Parameter 'GetDAMS_GEResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetDAMS_GE", ReplyAction:="http://tempuri.org/IService1/GetDAMS_GEResponse"),  _
     System.ServiceModel.XmlSerializerFormatAttribute(),  _
     System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object()))>  _
    Function GetDAMS_GE(ByVal request As GetDAMS_GERequest) As GetDAMS_GEResponse
    
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetDAMS_GE", ReplyAction:="http://tempuri.org/IService1/GetDAMS_GEResponse")>  _
    Function GetDAMS_GEAsync(ByVal request As GetDAMS_GERequest) As System.Threading.Tasks.Task(Of GetDAMS_GEResponse)
    
    'CODEGEN: Parameter 'GetLANDFILLS_GEResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetLANDFILLS_GE", ReplyAction:="http://tempuri.org/IService1/GetLANDFILLS_GEResponse"),  _
     System.ServiceModel.XmlSerializerFormatAttribute(),  _
     System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object()))>  _
    Function GetLANDFILLS_GE(ByVal request As GetLANDFILLS_GERequest) As GetLANDFILLS_GEResponse
    
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetLANDFILLS_GE", ReplyAction:="http://tempuri.org/IService1/GetLANDFILLS_GEResponse")>  _
    Function GetLANDFILLS_GEAsync(ByVal request As GetLANDFILLS_GERequest) As System.Threading.Tasks.Task(Of GetLANDFILLS_GEResponse)
    
    'CODEGEN: Parameter 'GetGOLF_GEResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetGOLF_GE", ReplyAction:="http://tempuri.org/IService1/GetGOLF_GEResponse"),  _
     System.ServiceModel.XmlSerializerFormatAttribute(),  _
     System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object()))>  _
    Function GetGOLF_GE(ByVal request As GetGOLF_GERequest) As GetGOLF_GEResponse
    
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetGOLF_GE", ReplyAction:="http://tempuri.org/IService1/GetGOLF_GEResponse")>  _
    Function GetGOLF_GEAsync(ByVal request As GetGOLF_GERequest) As System.Threading.Tasks.Task(Of GetGOLF_GEResponse)
    
    'CODEGEN: Parameter 'GetSTRIKES_GEResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetSTRIKES_GE", ReplyAction:="http://tempuri.org/IService1/GetSTRIKES_GEResponse"),  _
     System.ServiceModel.XmlSerializerFormatAttribute(),  _
     System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object()))>  _
    Function GetSTRIKES_GE(ByVal request As GetSTRIKES_GERequest) As GetSTRIKES_GEResponse
    
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetSTRIKES_GE", ReplyAction:="http://tempuri.org/IService1/GetSTRIKES_GEResponse")>  _
    Function GetSTRIKES_GEAsync(ByVal request As GetSTRIKES_GERequest) As System.Threading.Tasks.Task(Of GetSTRIKES_GEResponse)
    
    'CODEGEN: Parameter 'Get_GE_AreaResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/Get_GE_Area", ReplyAction:="http://tempuri.org/IService1/Get_GE_AreaResponse"),  _
     System.ServiceModel.XmlSerializerFormatAttribute(),  _
     System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object()))>  _
    Function Get_GE_Area(ByVal request As Get_GE_AreaRequest) As Get_GE_AreaResponse
    
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/Get_GE_Area", ReplyAction:="http://tempuri.org/IService1/Get_GE_AreaResponse")>  _
    Function Get_GE_AreaAsync(ByVal request As Get_GE_AreaRequest) As System.Threading.Tasks.Task(Of Get_GE_AreaResponse)
    
    'CODEGEN: Parameter 'Get_GEResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/Get_GE", ReplyAction:="http://tempuri.org/IService1/Get_GEResponse"),  _
     System.ServiceModel.XmlSerializerFormatAttribute(),  _
     System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object()))>  _
    Function Get_GE(ByVal request As Get_GERequest) As Get_GEResponse
    
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/Get_GE", ReplyAction:="http://tempuri.org/IService1/Get_GEResponse")>  _
    Function Get_GEAsync(ByVal request As Get_GERequest) As System.Threading.Tasks.Task(Of Get_GEResponse)
    
    'CODEGEN: Parameter 'Get_GE_DAMSResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/Get_GE_DAMS", ReplyAction:="http://tempuri.org/IService1/Get_GE_DAMSResponse"),  _
     System.ServiceModel.XmlSerializerFormatAttribute(),  _
     System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object()))>  _
    Function Get_GE_DAMS(ByVal request As Get_GE_DAMSRequest) As Get_GE_DAMSResponse
    
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/Get_GE_DAMS", ReplyAction:="http://tempuri.org/IService1/Get_GE_DAMSResponse")>  _
    Function Get_GE_DAMSAsync(ByVal request As Get_GE_DAMSRequest) As System.Threading.Tasks.Task(Of Get_GE_DAMSResponse)
    
    'CODEGEN: Parameter 'Get_GE_LANDFILLSResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/Get_GE_LANDFILLS", ReplyAction:="http://tempuri.org/IService1/Get_GE_LANDFILLSResponse"),  _
     System.ServiceModel.XmlSerializerFormatAttribute(),  _
     System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object()))>  _
    Function Get_GE_LANDFILLS(ByVal request As Get_GE_LANDFILLSRequest) As Get_GE_LANDFILLSResponse
    
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/Get_GE_LANDFILLS", ReplyAction:="http://tempuri.org/IService1/Get_GE_LANDFILLSResponse")>  _
    Function Get_GE_LANDFILLSAsync(ByVal request As Get_GE_LANDFILLSRequest) As System.Threading.Tasks.Task(Of Get_GE_LANDFILLSResponse)
    
    'CODEGEN: Parameter 'Get_GE_GOLFResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/Get_GE_GOLF", ReplyAction:="http://tempuri.org/IService1/Get_GE_GOLFResponse"),  _
     System.ServiceModel.XmlSerializerFormatAttribute(),  _
     System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object()))>  _
    Function Get_GE_GOLF(ByVal request As Get_GE_GOLFRequest) As Get_GE_GOLFResponse
    
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/Get_GE_GOLF", ReplyAction:="http://tempuri.org/IService1/Get_GE_GOLFResponse")>  _
    Function Get_GE_GOLFAsync(ByVal request As Get_GE_GOLFRequest) As System.Threading.Tasks.Task(Of Get_GE_GOLFResponse)
    
    'CODEGEN: Parameter 'Get_GE_STRIKES_ALLResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/Get_GE_STRIKES_ALL", ReplyAction:="http://tempuri.org/IService1/Get_GE_STRIKES_ALLResponse"),  _
     System.ServiceModel.XmlSerializerFormatAttribute(),  _
     System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object()))>  _
    Function Get_GE_STRIKES_ALL(ByVal request As Get_GE_STRIKES_ALLRequest) As Get_GE_STRIKES_ALLResponse
    
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/Get_GE_STRIKES_ALL", ReplyAction:="http://tempuri.org/IService1/Get_GE_STRIKES_ALLResponse")>  _
    Function Get_GE_STRIKES_ALLAsync(ByVal request As Get_GE_STRIKES_ALLRequest) As System.Threading.Tasks.Task(Of Get_GE_STRIKES_ALLResponse)
    
    'CODEGEN: Parameter 'GetSTRIKESAllResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetSTRIKESAll", ReplyAction:="http://tempuri.org/IService1/GetSTRIKESAllResponse"),  _
     System.ServiceModel.XmlSerializerFormatAttribute(),  _
     System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object()))>  _
    Function GetSTRIKESAll(ByVal request As GetSTRIKESAllRequest) As GetSTRIKESAllResponse
    
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetSTRIKESAll", ReplyAction:="http://tempuri.org/IService1/GetSTRIKESAllResponse")>  _
    Function GetSTRIKESAllAsync(ByVal request As GetSTRIKESAllRequest) As System.Threading.Tasks.Task(Of GetSTRIKESAllResponse)
    
    'CODEGEN: Parameter 'Get_GE_STRIKESResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/Get_GE_STRIKES", ReplyAction:="http://tempuri.org/IService1/Get_GE_STRIKESResponse"),  _
     System.ServiceModel.XmlSerializerFormatAttribute(),  _
     System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object()))>  _
    Function Get_GE_STRIKES(ByVal request As Get_GE_STRIKESRequest) As Get_GE_STRIKESResponse
    
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/Get_GE_STRIKES", ReplyAction:="http://tempuri.org/IService1/Get_GE_STRIKESResponse")>  _
    Function Get_GE_STRIKESAsync(ByVal request As Get_GE_STRIKESRequest) As System.Threading.Tasks.Task(Of Get_GE_STRIKESResponse)
    
    'CODEGEN: Parameter 'GetSTRIKES_IMGSResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetSTRIKES_IMGS", ReplyAction:="http://tempuri.org/IService1/GetSTRIKES_IMGSResponse"),  _
     System.ServiceModel.XmlSerializerFormatAttribute(),  _
     System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object()))>  _
    Function GetSTRIKES_IMGS(ByVal request As GetSTRIKES_IMGSRequest) As GetSTRIKES_IMGSResponse
    
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetSTRIKES_IMGS", ReplyAction:="http://tempuri.org/IService1/GetSTRIKES_IMGSResponse")>  _
    Function GetSTRIKES_IMGSAsync(ByVal request As GetSTRIKES_IMGSRequest) As System.Threading.Tasks.Task(Of GetSTRIKES_IMGSResponse)
End Interface

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="GetData", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
Partial Public Class GetDataRequest
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public value As String
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal value As String)
        MyBase.New
        Me.value = value
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="GetDataResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
Partial Public Class GetDataResponse
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public GetDataResult As String
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal GetDataResult As String)
        MyBase.New
        Me.GetDataResult = GetDataResult
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.18020"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/WCF_AHAS")>  _
Partial Public Class CompositeType
    
    Private boolValueField As Boolean
    
    Private boolValueFieldSpecified As Boolean
    
    Private stringValueField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
    Public Property BoolValue() As Boolean
        Get
            Return Me.boolValueField
        End Get
        Set
            Me.boolValueField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property BoolValueSpecified() As Boolean
        Get
            Return Me.boolValueFieldSpecified
        End Get
        Set
            Me.boolValueFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=1)>  _
    Public Property StringValue() As String
        Get
            Return Me.stringValueField
        End Get
        Set
            Me.stringValueField = value
        End Set
    End Property
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="GetDataUsingDataContract", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
Partial Public Class GetDataUsingDataContractRequest
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public composite As CompositeType
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal composite As CompositeType)
        MyBase.New
        Me.composite = composite
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="GetDataUsingDataContractResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
Partial Public Class GetDataUsingDataContractResponse
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public GetDataUsingDataContractResult As CompositeType
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal GetDataUsingDataContractResult As CompositeType)
        MyBase.New
        Me.GetDataUsingDataContractResult = GetDataUsingDataContractResult
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="GetAHASRisk", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
Partial Public Class GetAHASRiskRequest
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public Area As String
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public iMonth As String
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=2),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public iDay As String
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=3),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public iHour As String
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal Area As String, ByVal iMonth As String, ByVal iDay As String, ByVal iHour As String)
        MyBase.New
        Me.Area = Area
        Me.iMonth = iMonth
        Me.iDay = iDay
        Me.iHour = iHour
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="GetAHASRiskResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
Partial Public Class GetAHASRiskResponse
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public GetAHASRiskResult As String
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal GetAHASRiskResult As String)
        MyBase.New
        Me.GetAHASRiskResult = GetAHASRiskResult
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="GetAHASRisk12", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
Partial Public Class GetAHASRisk12Request
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public Area As String
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public iMonth As String
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=2),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public iDay As String
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=3),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public iHour As String
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal Area As String, ByVal iMonth As String, ByVal iDay As String, ByVal iHour As String)
        MyBase.New
        Me.Area = Area
        Me.iMonth = iMonth
        Me.iDay = iDay
        Me.iHour = iHour
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="GetAHASRisk12Response", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
Partial Public Class GetAHASRisk12Response
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public GetAHASRisk12Result As String
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal GetAHASRisk12Result As String)
        MyBase.New
        Me.GetAHASRisk12Result = GetAHASRisk12Result
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="GetUNITRisk", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
Partial Public Class GetUNITRiskRequest
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public Area As String
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public iMonth As String
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=2),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public iDay As String
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=3),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public iHour As String
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal Area As String, ByVal iMonth As String, ByVal iDay As String, ByVal iHour As String)
        MyBase.New
        Me.Area = Area
        Me.iMonth = iMonth
        Me.iDay = iDay
        Me.iHour = iHour
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="GetUNITRiskResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
Partial Public Class GetUNITRiskResponse
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public GetUNITRiskResult As String
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal GetUNITRiskResult As String)
        MyBase.New
        Me.GetUNITRiskResult = GetUNITRiskResult
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="GetUNITRisk12", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
Partial Public Class GetUNITRisk12Request
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public Area As String
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public iMonth As String
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=2),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public iDay As String
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=3),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public iHour As String
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal Area As String, ByVal iMonth As String, ByVal iDay As String, ByVal iHour As String)
        MyBase.New
        Me.Area = Area
        Me.iMonth = iMonth
        Me.iDay = iDay
        Me.iHour = iHour
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="GetUNITRisk12Response", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
Partial Public Class GetUNITRisk12Response
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public GetUNITRisk12Result As String
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal GetUNITRisk12Result As String)
        MyBase.New
        Me.GetUNITRisk12Result = GetUNITRisk12Result
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="GetDAMS", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
Partial Public Class GetDAMSRequest
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public Area As String
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal Area As String)
        MyBase.New
        Me.Area = Area
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="GetDAMSResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
Partial Public Class GetDAMSResponse
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public GetDAMSResult As String
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal GetDAMSResult As String)
        MyBase.New
        Me.GetDAMSResult = GetDAMSResult
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="GetLANDFILLS", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
Partial Public Class GetLANDFILLSRequest
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public Area As String
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal Area As String)
        MyBase.New
        Me.Area = Area
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="GetLANDFILLSResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
Partial Public Class GetLANDFILLSResponse
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public GetLANDFILLSResult As String
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal GetLANDFILLSResult As String)
        MyBase.New
        Me.GetLANDFILLSResult = GetLANDFILLSResult
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="GetGOLF", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
Partial Public Class GetGOLFRequest
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public Area As String
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal Area As String)
        MyBase.New
        Me.Area = Area
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="GetGOLFResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
Partial Public Class GetGOLFResponse
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public GetGOLFResult As String
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal GetGOLFResult As String)
        MyBase.New
        Me.GetGOLFResult = GetGOLFResult
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="GetSTRIKES", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
Partial Public Class GetSTRIKESRequest
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public Area As String
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal Area As String)
        MyBase.New
        Me.Area = Area
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="GetSTRIKESResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
Partial Public Class GetSTRIKESResponse
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public GetSTRIKESResult As String
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal GetSTRIKESResult As String)
        MyBase.New
        Me.GetSTRIKESResult = GetSTRIKESResult
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="GetDAMS_GE", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
Partial Public Class GetDAMS_GERequest
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public Area As String
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal Area As String)
        MyBase.New
        Me.Area = Area
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="GetDAMS_GEResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
Partial Public Class GetDAMS_GEResponse
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public GetDAMS_GEResult As System.Data.DataSet
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal GetDAMS_GEResult As System.Data.DataSet)
        MyBase.New
        Me.GetDAMS_GEResult = GetDAMS_GEResult
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="GetLANDFILLS_GE", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
Partial Public Class GetLANDFILLS_GERequest
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public Area As String
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal Area As String)
        MyBase.New
        Me.Area = Area
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="GetLANDFILLS_GEResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
Partial Public Class GetLANDFILLS_GEResponse
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public GetLANDFILLS_GEResult As System.Data.DataSet
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal GetLANDFILLS_GEResult As System.Data.DataSet)
        MyBase.New
        Me.GetLANDFILLS_GEResult = GetLANDFILLS_GEResult
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="GetGOLF_GE", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
Partial Public Class GetGOLF_GERequest
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public Area As String
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal Area As String)
        MyBase.New
        Me.Area = Area
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="GetGOLF_GEResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
Partial Public Class GetGOLF_GEResponse
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public GetGOLF_GEResult As System.Data.DataSet
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal GetGOLF_GEResult As System.Data.DataSet)
        MyBase.New
        Me.GetGOLF_GEResult = GetGOLF_GEResult
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="GetSTRIKES_GE", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
Partial Public Class GetSTRIKES_GERequest
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public Area As String
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal Area As String)
        MyBase.New
        Me.Area = Area
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="GetSTRIKES_GEResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
Partial Public Class GetSTRIKES_GEResponse
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public GetSTRIKES_GEResult As System.Data.DataSet
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal GetSTRIKES_GEResult As System.Data.DataSet)
        MyBase.New
        Me.GetSTRIKES_GEResult = GetSTRIKES_GEResult
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="Get_GE_Area", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
Partial Public Class Get_GE_AreaRequest
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public sArea As String
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal sArea As String)
        MyBase.New
        Me.sArea = sArea
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="Get_GE_AreaResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
Partial Public Class Get_GE_AreaResponse
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
     System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true),  _
     System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.microsoft.com/2003/10/Serialization/Arrays")>  _
    Public Get_GE_AreaResult() As Object
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal Get_GE_AreaResult() As Object)
        MyBase.New
        Me.Get_GE_AreaResult = Get_GE_AreaResult
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="Get_GE", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
Partial Public Class Get_GERequest
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public Area As String
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal Area As String)
        MyBase.New
        Me.Area = Area
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="Get_GEResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
Partial Public Class Get_GEResponse
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
     System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true),  _
     System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.microsoft.com/2003/10/Serialization/Arrays")>  _
    Public Get_GEResult() As Object
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal Get_GEResult() As Object)
        MyBase.New
        Me.Get_GEResult = Get_GEResult
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="Get_GE_DAMS", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
Partial Public Class Get_GE_DAMSRequest
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public Area As String
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal Area As String)
        MyBase.New
        Me.Area = Area
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="Get_GE_DAMSResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
Partial Public Class Get_GE_DAMSResponse
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
     System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true),  _
     System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.microsoft.com/2003/10/Serialization/Arrays")>  _
    Public Get_GE_DAMSResult() As Object
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal Get_GE_DAMSResult() As Object)
        MyBase.New
        Me.Get_GE_DAMSResult = Get_GE_DAMSResult
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="Get_GE_LANDFILLS", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
Partial Public Class Get_GE_LANDFILLSRequest
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public Area As String
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal Area As String)
        MyBase.New
        Me.Area = Area
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="Get_GE_LANDFILLSResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
Partial Public Class Get_GE_LANDFILLSResponse
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
     System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true),  _
     System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.microsoft.com/2003/10/Serialization/Arrays")>  _
    Public Get_GE_LANDFILLSResult() As Object
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal Get_GE_LANDFILLSResult() As Object)
        MyBase.New
        Me.Get_GE_LANDFILLSResult = Get_GE_LANDFILLSResult
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="Get_GE_GOLF", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
Partial Public Class Get_GE_GOLFRequest
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public Area As String
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal Area As String)
        MyBase.New
        Me.Area = Area
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="Get_GE_GOLFResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
Partial Public Class Get_GE_GOLFResponse
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
     System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true),  _
     System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.microsoft.com/2003/10/Serialization/Arrays")>  _
    Public Get_GE_GOLFResult() As Object
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal Get_GE_GOLFResult() As Object)
        MyBase.New
        Me.Get_GE_GOLFResult = Get_GE_GOLFResult
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="Get_GE_STRIKES_ALL", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
Partial Public Class Get_GE_STRIKES_ALLRequest
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public sClass1 As String
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal sClass1 As String)
        MyBase.New
        Me.sClass1 = sClass1
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="Get_GE_STRIKES_ALLResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
Partial Public Class Get_GE_STRIKES_ALLResponse
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
     System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true),  _
     System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.microsoft.com/2003/10/Serialization/Arrays")>  _
    Public Get_GE_STRIKES_ALLResult() As Object
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal Get_GE_STRIKES_ALLResult() As Object)
        MyBase.New
        Me.Get_GE_STRIKES_ALLResult = Get_GE_STRIKES_ALLResult
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="GetSTRIKESAll", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
Partial Public Class GetSTRIKESAllRequest
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public sClass As String
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal sClass As String)
        MyBase.New
        Me.sClass = sClass
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="GetSTRIKESAllResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
Partial Public Class GetSTRIKESAllResponse
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public GetSTRIKESAllResult As System.Data.DataSet
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal GetSTRIKESAllResult As System.Data.DataSet)
        MyBase.New
        Me.GetSTRIKESAllResult = GetSTRIKESAllResult
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="Get_GE_STRIKES", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
Partial Public Class Get_GE_STRIKESRequest
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public Area As String
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal Area As String)
        MyBase.New
        Me.Area = Area
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="Get_GE_STRIKESResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
Partial Public Class Get_GE_STRIKESResponse
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
     System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true),  _
     System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.microsoft.com/2003/10/Serialization/Arrays")>  _
    Public Get_GE_STRIKESResult() As Object
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal Get_GE_STRIKESResult() As Object)
        MyBase.New
        Me.Get_GE_STRIKESResult = Get_GE_STRIKESResult
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="GetSTRIKES_IMGS", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
Partial Public Class GetSTRIKES_IMGSRequest
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public Area As String
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal Area As String)
        MyBase.New
        Me.Area = Area
    End Sub
End Class

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
 System.ServiceModel.MessageContractAttribute(WrapperName:="GetSTRIKES_IMGSResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
Partial Public Class GetSTRIKES_IMGSResponse
    
    <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
     System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public GetSTRIKES_IMGSResult As System.Data.DataSet
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal GetSTRIKES_IMGSResult As System.Data.DataSet)
        MyBase.New
        Me.GetSTRIKES_IMGSResult = GetSTRIKES_IMGSResult
    End Sub
End Class

<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
Public Interface IService1Channel
    Inherits IService1, System.ServiceModel.IClientChannel
End Interface

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
Partial Public Class Service1Client
    Inherits System.ServiceModel.ClientBase(Of IService1)
    Implements IService1
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String)
        MyBase.New(endpointConfigurationName)
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub
    
    Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(binding, remoteAddress)
    End Sub
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IService1_GetData(ByVal request As GetDataRequest) As GetDataResponse Implements IService1.GetData
        Return MyBase.Channel.GetData(request)
    End Function
    
    Public Function GetData(ByVal value As String) As String
        Dim inValue As GetDataRequest = New GetDataRequest()
        inValue.value = value
        Dim retVal As GetDataResponse = CType(Me,IService1).GetData(inValue)
        Return retVal.GetDataResult
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IService1_GetDataAsync(ByVal request As GetDataRequest) As System.Threading.Tasks.Task(Of GetDataResponse) Implements IService1.GetDataAsync
        Return MyBase.Channel.GetDataAsync(request)
    End Function
    
    Public Function GetDataAsync(ByVal value As String) As System.Threading.Tasks.Task(Of GetDataResponse)
        Dim inValue As GetDataRequest = New GetDataRequest()
        inValue.value = value
        Return CType(Me,IService1).GetDataAsync(inValue)
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IService1_GetDataUsingDataContract(ByVal request As GetDataUsingDataContractRequest) As GetDataUsingDataContractResponse Implements IService1.GetDataUsingDataContract
        Return MyBase.Channel.GetDataUsingDataContract(request)
    End Function
    
    Public Function GetDataUsingDataContract(ByVal composite As CompositeType) As CompositeType
        Dim inValue As GetDataUsingDataContractRequest = New GetDataUsingDataContractRequest()
        inValue.composite = composite
        Dim retVal As GetDataUsingDataContractResponse = CType(Me,IService1).GetDataUsingDataContract(inValue)
        Return retVal.GetDataUsingDataContractResult
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IService1_GetDataUsingDataContractAsync(ByVal request As GetDataUsingDataContractRequest) As System.Threading.Tasks.Task(Of GetDataUsingDataContractResponse) Implements IService1.GetDataUsingDataContractAsync
        Return MyBase.Channel.GetDataUsingDataContractAsync(request)
    End Function
    
    Public Function GetDataUsingDataContractAsync(ByVal composite As CompositeType) As System.Threading.Tasks.Task(Of GetDataUsingDataContractResponse)
        Dim inValue As GetDataUsingDataContractRequest = New GetDataUsingDataContractRequest()
        inValue.composite = composite
        Return CType(Me,IService1).GetDataUsingDataContractAsync(inValue)
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IService1_GetAHASRisk(ByVal request As GetAHASRiskRequest) As GetAHASRiskResponse Implements IService1.GetAHASRisk
        Return MyBase.Channel.GetAHASRisk(request)
    End Function
    
    Public Function GetAHASRisk(ByVal Area As String, ByVal iMonth As String, ByVal iDay As String, ByVal iHour As String) As String
        Dim inValue As GetAHASRiskRequest = New GetAHASRiskRequest()
        inValue.Area = Area
        inValue.iMonth = iMonth
        inValue.iDay = iDay
        inValue.iHour = iHour
        Dim retVal As GetAHASRiskResponse = CType(Me,IService1).GetAHASRisk(inValue)
        Return retVal.GetAHASRiskResult
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IService1_GetAHASRiskAsync(ByVal request As GetAHASRiskRequest) As System.Threading.Tasks.Task(Of GetAHASRiskResponse) Implements IService1.GetAHASRiskAsync
        Return MyBase.Channel.GetAHASRiskAsync(request)
    End Function
    
    Public Function GetAHASRiskAsync(ByVal Area As String, ByVal iMonth As String, ByVal iDay As String, ByVal iHour As String) As System.Threading.Tasks.Task(Of GetAHASRiskResponse)
        Dim inValue As GetAHASRiskRequest = New GetAHASRiskRequest()
        inValue.Area = Area
        inValue.iMonth = iMonth
        inValue.iDay = iDay
        inValue.iHour = iHour
        Return CType(Me,IService1).GetAHASRiskAsync(inValue)
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IService1_GetAHASRisk12(ByVal request As GetAHASRisk12Request) As GetAHASRisk12Response Implements IService1.GetAHASRisk12
        Return MyBase.Channel.GetAHASRisk12(request)
    End Function
    
    Public Function GetAHASRisk12(ByVal Area As String, ByVal iMonth As String, ByVal iDay As String, ByVal iHour As String) As String
        Dim inValue As GetAHASRisk12Request = New GetAHASRisk12Request()
        inValue.Area = Area
        inValue.iMonth = iMonth
        inValue.iDay = iDay
        inValue.iHour = iHour
        Dim retVal As GetAHASRisk12Response = CType(Me,IService1).GetAHASRisk12(inValue)
        Return retVal.GetAHASRisk12Result
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IService1_GetAHASRisk12Async(ByVal request As GetAHASRisk12Request) As System.Threading.Tasks.Task(Of GetAHASRisk12Response) Implements IService1.GetAHASRisk12Async
        Return MyBase.Channel.GetAHASRisk12Async(request)
    End Function
    
    Public Function GetAHASRisk12Async(ByVal Area As String, ByVal iMonth As String, ByVal iDay As String, ByVal iHour As String) As System.Threading.Tasks.Task(Of GetAHASRisk12Response)
        Dim inValue As GetAHASRisk12Request = New GetAHASRisk12Request()
        inValue.Area = Area
        inValue.iMonth = iMonth
        inValue.iDay = iDay
        inValue.iHour = iHour
        Return CType(Me,IService1).GetAHASRisk12Async(inValue)
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IService1_GetUNITRisk(ByVal request As GetUNITRiskRequest) As GetUNITRiskResponse Implements IService1.GetUNITRisk
        Return MyBase.Channel.GetUNITRisk(request)
    End Function
    
    Public Function GetUNITRisk(ByVal Area As String, ByVal iMonth As String, ByVal iDay As String, ByVal iHour As String) As String
        Dim inValue As GetUNITRiskRequest = New GetUNITRiskRequest()
        inValue.Area = Area
        inValue.iMonth = iMonth
        inValue.iDay = iDay
        inValue.iHour = iHour
        Dim retVal As GetUNITRiskResponse = CType(Me,IService1).GetUNITRisk(inValue)
        Return retVal.GetUNITRiskResult
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IService1_GetUNITRiskAsync(ByVal request As GetUNITRiskRequest) As System.Threading.Tasks.Task(Of GetUNITRiskResponse) Implements IService1.GetUNITRiskAsync
        Return MyBase.Channel.GetUNITRiskAsync(request)
    End Function
    
    Public Function GetUNITRiskAsync(ByVal Area As String, ByVal iMonth As String, ByVal iDay As String, ByVal iHour As String) As System.Threading.Tasks.Task(Of GetUNITRiskResponse)
        Dim inValue As GetUNITRiskRequest = New GetUNITRiskRequest()
        inValue.Area = Area
        inValue.iMonth = iMonth
        inValue.iDay = iDay
        inValue.iHour = iHour
        Return CType(Me,IService1).GetUNITRiskAsync(inValue)
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IService1_GetUNITRisk12(ByVal request As GetUNITRisk12Request) As GetUNITRisk12Response Implements IService1.GetUNITRisk12
        Return MyBase.Channel.GetUNITRisk12(request)
    End Function
    
    Public Function GetUNITRisk12(ByVal Area As String, ByVal iMonth As String, ByVal iDay As String, ByVal iHour As String) As String
        Dim inValue As GetUNITRisk12Request = New GetUNITRisk12Request()
        inValue.Area = Area
        inValue.iMonth = iMonth
        inValue.iDay = iDay
        inValue.iHour = iHour
        Dim retVal As GetUNITRisk12Response = CType(Me,IService1).GetUNITRisk12(inValue)
        Return retVal.GetUNITRisk12Result
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IService1_GetUNITRisk12Async(ByVal request As GetUNITRisk12Request) As System.Threading.Tasks.Task(Of GetUNITRisk12Response) Implements IService1.GetUNITRisk12Async
        Return MyBase.Channel.GetUNITRisk12Async(request)
    End Function
    
    Public Function GetUNITRisk12Async(ByVal Area As String, ByVal iMonth As String, ByVal iDay As String, ByVal iHour As String) As System.Threading.Tasks.Task(Of GetUNITRisk12Response)
        Dim inValue As GetUNITRisk12Request = New GetUNITRisk12Request()
        inValue.Area = Area
        inValue.iMonth = iMonth
        inValue.iDay = iDay
        inValue.iHour = iHour
        Return CType(Me,IService1).GetUNITRisk12Async(inValue)
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IService1_GetDAMS(ByVal request As GetDAMSRequest) As GetDAMSResponse Implements IService1.GetDAMS
        Return MyBase.Channel.GetDAMS(request)
    End Function
    
    Public Function GetDAMS(ByVal Area As String) As String
        Dim inValue As GetDAMSRequest = New GetDAMSRequest()
        inValue.Area = Area
        Dim retVal As GetDAMSResponse = CType(Me,IService1).GetDAMS(inValue)
        Return retVal.GetDAMSResult
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IService1_GetDAMSAsync(ByVal request As GetDAMSRequest) As System.Threading.Tasks.Task(Of GetDAMSResponse) Implements IService1.GetDAMSAsync
        Return MyBase.Channel.GetDAMSAsync(request)
    End Function
    
    Public Function GetDAMSAsync(ByVal Area As String) As System.Threading.Tasks.Task(Of GetDAMSResponse)
        Dim inValue As GetDAMSRequest = New GetDAMSRequest()
        inValue.Area = Area
        Return CType(Me,IService1).GetDAMSAsync(inValue)
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IService1_GetLANDFILLS(ByVal request As GetLANDFILLSRequest) As GetLANDFILLSResponse Implements IService1.GetLANDFILLS
        Return MyBase.Channel.GetLANDFILLS(request)
    End Function
    
    Public Function GetLANDFILLS(ByVal Area As String) As String
        Dim inValue As GetLANDFILLSRequest = New GetLANDFILLSRequest()
        inValue.Area = Area
        Dim retVal As GetLANDFILLSResponse = CType(Me,IService1).GetLANDFILLS(inValue)
        Return retVal.GetLANDFILLSResult
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IService1_GetLANDFILLSAsync(ByVal request As GetLANDFILLSRequest) As System.Threading.Tasks.Task(Of GetLANDFILLSResponse) Implements IService1.GetLANDFILLSAsync
        Return MyBase.Channel.GetLANDFILLSAsync(request)
    End Function
    
    Public Function GetLANDFILLSAsync(ByVal Area As String) As System.Threading.Tasks.Task(Of GetLANDFILLSResponse)
        Dim inValue As GetLANDFILLSRequest = New GetLANDFILLSRequest()
        inValue.Area = Area
        Return CType(Me,IService1).GetLANDFILLSAsync(inValue)
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IService1_GetGOLF(ByVal request As GetGOLFRequest) As GetGOLFResponse Implements IService1.GetGOLF
        Return MyBase.Channel.GetGOLF(request)
    End Function
    
    Public Function GetGOLF(ByVal Area As String) As String
        Dim inValue As GetGOLFRequest = New GetGOLFRequest()
        inValue.Area = Area
        Dim retVal As GetGOLFResponse = CType(Me,IService1).GetGOLF(inValue)
        Return retVal.GetGOLFResult
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IService1_GetGOLFAsync(ByVal request As GetGOLFRequest) As System.Threading.Tasks.Task(Of GetGOLFResponse) Implements IService1.GetGOLFAsync
        Return MyBase.Channel.GetGOLFAsync(request)
    End Function
    
    Public Function GetGOLFAsync(ByVal Area As String) As System.Threading.Tasks.Task(Of GetGOLFResponse)
        Dim inValue As GetGOLFRequest = New GetGOLFRequest()
        inValue.Area = Area
        Return CType(Me,IService1).GetGOLFAsync(inValue)
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IService1_GetSTRIKES(ByVal request As GetSTRIKESRequest) As GetSTRIKESResponse Implements IService1.GetSTRIKES
        Return MyBase.Channel.GetSTRIKES(request)
    End Function
    
    Public Function GetSTRIKES(ByVal Area As String) As String
        Dim inValue As GetSTRIKESRequest = New GetSTRIKESRequest()
        inValue.Area = Area
        Dim retVal As GetSTRIKESResponse = CType(Me,IService1).GetSTRIKES(inValue)
        Return retVal.GetSTRIKESResult
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IService1_GetSTRIKESAsync(ByVal request As GetSTRIKESRequest) As System.Threading.Tasks.Task(Of GetSTRIKESResponse) Implements IService1.GetSTRIKESAsync
        Return MyBase.Channel.GetSTRIKESAsync(request)
    End Function
    
    Public Function GetSTRIKESAsync(ByVal Area As String) As System.Threading.Tasks.Task(Of GetSTRIKESResponse)
        Dim inValue As GetSTRIKESRequest = New GetSTRIKESRequest()
        inValue.Area = Area
        Return CType(Me,IService1).GetSTRIKESAsync(inValue)
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IService1_GetDAMS_GE(ByVal request As GetDAMS_GERequest) As GetDAMS_GEResponse Implements IService1.GetDAMS_GE
        Return MyBase.Channel.GetDAMS_GE(request)
    End Function
    
    Public Function GetDAMS_GE(ByVal Area As String) As System.Data.DataSet
        Dim inValue As GetDAMS_GERequest = New GetDAMS_GERequest()
        inValue.Area = Area
        Dim retVal As GetDAMS_GEResponse = CType(Me,IService1).GetDAMS_GE(inValue)
        Return retVal.GetDAMS_GEResult
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IService1_GetDAMS_GEAsync(ByVal request As GetDAMS_GERequest) As System.Threading.Tasks.Task(Of GetDAMS_GEResponse) Implements IService1.GetDAMS_GEAsync
        Return MyBase.Channel.GetDAMS_GEAsync(request)
    End Function
    
    Public Function GetDAMS_GEAsync(ByVal Area As String) As System.Threading.Tasks.Task(Of GetDAMS_GEResponse)
        Dim inValue As GetDAMS_GERequest = New GetDAMS_GERequest()
        inValue.Area = Area
        Return CType(Me,IService1).GetDAMS_GEAsync(inValue)
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IService1_GetLANDFILLS_GE(ByVal request As GetLANDFILLS_GERequest) As GetLANDFILLS_GEResponse Implements IService1.GetLANDFILLS_GE
        Return MyBase.Channel.GetLANDFILLS_GE(request)
    End Function
    
    Public Function GetLANDFILLS_GE(ByVal Area As String) As System.Data.DataSet
        Dim inValue As GetLANDFILLS_GERequest = New GetLANDFILLS_GERequest()
        inValue.Area = Area
        Dim retVal As GetLANDFILLS_GEResponse = CType(Me,IService1).GetLANDFILLS_GE(inValue)
        Return retVal.GetLANDFILLS_GEResult
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IService1_GetLANDFILLS_GEAsync(ByVal request As GetLANDFILLS_GERequest) As System.Threading.Tasks.Task(Of GetLANDFILLS_GEResponse) Implements IService1.GetLANDFILLS_GEAsync
        Return MyBase.Channel.GetLANDFILLS_GEAsync(request)
    End Function
    
    Public Function GetLANDFILLS_GEAsync(ByVal Area As String) As System.Threading.Tasks.Task(Of GetLANDFILLS_GEResponse)
        Dim inValue As GetLANDFILLS_GERequest = New GetLANDFILLS_GERequest()
        inValue.Area = Area
        Return CType(Me,IService1).GetLANDFILLS_GEAsync(inValue)
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IService1_GetGOLF_GE(ByVal request As GetGOLF_GERequest) As GetGOLF_GEResponse Implements IService1.GetGOLF_GE
        Return MyBase.Channel.GetGOLF_GE(request)
    End Function
    
    Public Function GetGOLF_GE(ByVal Area As String) As System.Data.DataSet
        Dim inValue As GetGOLF_GERequest = New GetGOLF_GERequest()
        inValue.Area = Area
        Dim retVal As GetGOLF_GEResponse = CType(Me,IService1).GetGOLF_GE(inValue)
        Return retVal.GetGOLF_GEResult
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IService1_GetGOLF_GEAsync(ByVal request As GetGOLF_GERequest) As System.Threading.Tasks.Task(Of GetGOLF_GEResponse) Implements IService1.GetGOLF_GEAsync
        Return MyBase.Channel.GetGOLF_GEAsync(request)
    End Function
    
    Public Function GetGOLF_GEAsync(ByVal Area As String) As System.Threading.Tasks.Task(Of GetGOLF_GEResponse)
        Dim inValue As GetGOLF_GERequest = New GetGOLF_GERequest()
        inValue.Area = Area
        Return CType(Me,IService1).GetGOLF_GEAsync(inValue)
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IService1_GetSTRIKES_GE(ByVal request As GetSTRIKES_GERequest) As GetSTRIKES_GEResponse Implements IService1.GetSTRIKES_GE
        Return MyBase.Channel.GetSTRIKES_GE(request)
    End Function
    
    Public Function GetSTRIKES_GE(ByVal Area As String) As System.Data.DataSet
        Dim inValue As GetSTRIKES_GERequest = New GetSTRIKES_GERequest()
        inValue.Area = Area
        Dim retVal As GetSTRIKES_GEResponse = CType(Me,IService1).GetSTRIKES_GE(inValue)
        Return retVal.GetSTRIKES_GEResult
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IService1_GetSTRIKES_GEAsync(ByVal request As GetSTRIKES_GERequest) As System.Threading.Tasks.Task(Of GetSTRIKES_GEResponse) Implements IService1.GetSTRIKES_GEAsync
        Return MyBase.Channel.GetSTRIKES_GEAsync(request)
    End Function
    
    Public Function GetSTRIKES_GEAsync(ByVal Area As String) As System.Threading.Tasks.Task(Of GetSTRIKES_GEResponse)
        Dim inValue As GetSTRIKES_GERequest = New GetSTRIKES_GERequest()
        inValue.Area = Area
        Return CType(Me,IService1).GetSTRIKES_GEAsync(inValue)
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IService1_Get_GE_Area(ByVal request As Get_GE_AreaRequest) As Get_GE_AreaResponse Implements IService1.Get_GE_Area
        Return MyBase.Channel.Get_GE_Area(request)
    End Function
    
    Public Function Get_GE_Area(ByVal sArea As String) As Object()
        Dim inValue As Get_GE_AreaRequest = New Get_GE_AreaRequest()
        inValue.sArea = sArea
        Dim retVal As Get_GE_AreaResponse = CType(Me,IService1).Get_GE_Area(inValue)
        Return retVal.Get_GE_AreaResult
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IService1_Get_GE_AreaAsync(ByVal request As Get_GE_AreaRequest) As System.Threading.Tasks.Task(Of Get_GE_AreaResponse) Implements IService1.Get_GE_AreaAsync
        Return MyBase.Channel.Get_GE_AreaAsync(request)
    End Function
    
    Public Function Get_GE_AreaAsync(ByVal sArea As String) As System.Threading.Tasks.Task(Of Get_GE_AreaResponse)
        Dim inValue As Get_GE_AreaRequest = New Get_GE_AreaRequest()
        inValue.sArea = sArea
        Return CType(Me,IService1).Get_GE_AreaAsync(inValue)
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IService1_Get_GE(ByVal request As Get_GERequest) As Get_GEResponse Implements IService1.Get_GE
        Return MyBase.Channel.Get_GE(request)
    End Function
    
    Public Function Get_GE(ByVal Area As String) As Object()
        Dim inValue As Get_GERequest = New Get_GERequest()
        inValue.Area = Area
        Dim retVal As Get_GEResponse = CType(Me,IService1).Get_GE(inValue)
        Return retVal.Get_GEResult
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IService1_Get_GEAsync(ByVal request As Get_GERequest) As System.Threading.Tasks.Task(Of Get_GEResponse) Implements IService1.Get_GEAsync
        Return MyBase.Channel.Get_GEAsync(request)
    End Function
    
    Public Function Get_GEAsync(ByVal Area As String) As System.Threading.Tasks.Task(Of Get_GEResponse)
        Dim inValue As Get_GERequest = New Get_GERequest()
        inValue.Area = Area
        Return CType(Me,IService1).Get_GEAsync(inValue)
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IService1_Get_GE_DAMS(ByVal request As Get_GE_DAMSRequest) As Get_GE_DAMSResponse Implements IService1.Get_GE_DAMS
        Return MyBase.Channel.Get_GE_DAMS(request)
    End Function
    
    Public Function Get_GE_DAMS(ByVal Area As String) As Object()
        Dim inValue As Get_GE_DAMSRequest = New Get_GE_DAMSRequest()
        inValue.Area = Area
        Dim retVal As Get_GE_DAMSResponse = CType(Me,IService1).Get_GE_DAMS(inValue)
        Return retVal.Get_GE_DAMSResult
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IService1_Get_GE_DAMSAsync(ByVal request As Get_GE_DAMSRequest) As System.Threading.Tasks.Task(Of Get_GE_DAMSResponse) Implements IService1.Get_GE_DAMSAsync
        Return MyBase.Channel.Get_GE_DAMSAsync(request)
    End Function
    
    Public Function Get_GE_DAMSAsync(ByVal Area As String) As System.Threading.Tasks.Task(Of Get_GE_DAMSResponse)
        Dim inValue As Get_GE_DAMSRequest = New Get_GE_DAMSRequest()
        inValue.Area = Area
        Return CType(Me,IService1).Get_GE_DAMSAsync(inValue)
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IService1_Get_GE_LANDFILLS(ByVal request As Get_GE_LANDFILLSRequest) As Get_GE_LANDFILLSResponse Implements IService1.Get_GE_LANDFILLS
        Return MyBase.Channel.Get_GE_LANDFILLS(request)
    End Function
    
    Public Function Get_GE_LANDFILLS(ByVal Area As String) As Object()
        Dim inValue As Get_GE_LANDFILLSRequest = New Get_GE_LANDFILLSRequest()
        inValue.Area = Area
        Dim retVal As Get_GE_LANDFILLSResponse = CType(Me,IService1).Get_GE_LANDFILLS(inValue)
        Return retVal.Get_GE_LANDFILLSResult
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IService1_Get_GE_LANDFILLSAsync(ByVal request As Get_GE_LANDFILLSRequest) As System.Threading.Tasks.Task(Of Get_GE_LANDFILLSResponse) Implements IService1.Get_GE_LANDFILLSAsync
        Return MyBase.Channel.Get_GE_LANDFILLSAsync(request)
    End Function
    
    Public Function Get_GE_LANDFILLSAsync(ByVal Area As String) As System.Threading.Tasks.Task(Of Get_GE_LANDFILLSResponse)
        Dim inValue As Get_GE_LANDFILLSRequest = New Get_GE_LANDFILLSRequest()
        inValue.Area = Area
        Return CType(Me,IService1).Get_GE_LANDFILLSAsync(inValue)
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IService1_Get_GE_GOLF(ByVal request As Get_GE_GOLFRequest) As Get_GE_GOLFResponse Implements IService1.Get_GE_GOLF
        Return MyBase.Channel.Get_GE_GOLF(request)
    End Function
    
    Public Function Get_GE_GOLF(ByVal Area As String) As Object()
        Dim inValue As Get_GE_GOLFRequest = New Get_GE_GOLFRequest()
        inValue.Area = Area
        Dim retVal As Get_GE_GOLFResponse = CType(Me,IService1).Get_GE_GOLF(inValue)
        Return retVal.Get_GE_GOLFResult
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IService1_Get_GE_GOLFAsync(ByVal request As Get_GE_GOLFRequest) As System.Threading.Tasks.Task(Of Get_GE_GOLFResponse) Implements IService1.Get_GE_GOLFAsync
        Return MyBase.Channel.Get_GE_GOLFAsync(request)
    End Function
    
    Public Function Get_GE_GOLFAsync(ByVal Area As String) As System.Threading.Tasks.Task(Of Get_GE_GOLFResponse)
        Dim inValue As Get_GE_GOLFRequest = New Get_GE_GOLFRequest()
        inValue.Area = Area
        Return CType(Me,IService1).Get_GE_GOLFAsync(inValue)
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IService1_Get_GE_STRIKES_ALL(ByVal request As Get_GE_STRIKES_ALLRequest) As Get_GE_STRIKES_ALLResponse Implements IService1.Get_GE_STRIKES_ALL
        Return MyBase.Channel.Get_GE_STRIKES_ALL(request)
    End Function
    
    Public Function Get_GE_STRIKES_ALL(ByVal sClass1 As String) As Object()
        Dim inValue As Get_GE_STRIKES_ALLRequest = New Get_GE_STRIKES_ALLRequest()
        inValue.sClass1 = sClass1
        Dim retVal As Get_GE_STRIKES_ALLResponse = CType(Me,IService1).Get_GE_STRIKES_ALL(inValue)
        Return retVal.Get_GE_STRIKES_ALLResult
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IService1_Get_GE_STRIKES_ALLAsync(ByVal request As Get_GE_STRIKES_ALLRequest) As System.Threading.Tasks.Task(Of Get_GE_STRIKES_ALLResponse) Implements IService1.Get_GE_STRIKES_ALLAsync
        Return MyBase.Channel.Get_GE_STRIKES_ALLAsync(request)
    End Function
    
    Public Function Get_GE_STRIKES_ALLAsync(ByVal sClass1 As String) As System.Threading.Tasks.Task(Of Get_GE_STRIKES_ALLResponse)
        Dim inValue As Get_GE_STRIKES_ALLRequest = New Get_GE_STRIKES_ALLRequest()
        inValue.sClass1 = sClass1
        Return CType(Me,IService1).Get_GE_STRIKES_ALLAsync(inValue)
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IService1_GetSTRIKESAll(ByVal request As GetSTRIKESAllRequest) As GetSTRIKESAllResponse Implements IService1.GetSTRIKESAll
        Return MyBase.Channel.GetSTRIKESAll(request)
    End Function
    
    Public Function GetSTRIKESAll(ByVal sClass As String) As System.Data.DataSet
        Dim inValue As GetSTRIKESAllRequest = New GetSTRIKESAllRequest()
        inValue.sClass = sClass
        Dim retVal As GetSTRIKESAllResponse = CType(Me,IService1).GetSTRIKESAll(inValue)
        Return retVal.GetSTRIKESAllResult
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IService1_GetSTRIKESAllAsync(ByVal request As GetSTRIKESAllRequest) As System.Threading.Tasks.Task(Of GetSTRIKESAllResponse) Implements IService1.GetSTRIKESAllAsync
        Return MyBase.Channel.GetSTRIKESAllAsync(request)
    End Function
    
    Public Function GetSTRIKESAllAsync(ByVal sClass As String) As System.Threading.Tasks.Task(Of GetSTRIKESAllResponse)
        Dim inValue As GetSTRIKESAllRequest = New GetSTRIKESAllRequest()
        inValue.sClass = sClass
        Return CType(Me,IService1).GetSTRIKESAllAsync(inValue)
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IService1_Get_GE_STRIKES(ByVal request As Get_GE_STRIKESRequest) As Get_GE_STRIKESResponse Implements IService1.Get_GE_STRIKES
        Return MyBase.Channel.Get_GE_STRIKES(request)
    End Function
    
    Public Function Get_GE_STRIKES(ByVal Area As String) As Object()
        Dim inValue As Get_GE_STRIKESRequest = New Get_GE_STRIKESRequest()
        inValue.Area = Area
        Dim retVal As Get_GE_STRIKESResponse = CType(Me,IService1).Get_GE_STRIKES(inValue)
        Return retVal.Get_GE_STRIKESResult
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IService1_Get_GE_STRIKESAsync(ByVal request As Get_GE_STRIKESRequest) As System.Threading.Tasks.Task(Of Get_GE_STRIKESResponse) Implements IService1.Get_GE_STRIKESAsync
        Return MyBase.Channel.Get_GE_STRIKESAsync(request)
    End Function
    
    Public Function Get_GE_STRIKESAsync(ByVal Area As String) As System.Threading.Tasks.Task(Of Get_GE_STRIKESResponse)
        Dim inValue As Get_GE_STRIKESRequest = New Get_GE_STRIKESRequest()
        inValue.Area = Area
        Return CType(Me,IService1).Get_GE_STRIKESAsync(inValue)
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IService1_GetSTRIKES_IMGS(ByVal request As GetSTRIKES_IMGSRequest) As GetSTRIKES_IMGSResponse Implements IService1.GetSTRIKES_IMGS
        Return MyBase.Channel.GetSTRIKES_IMGS(request)
    End Function
    
    Public Function GetSTRIKES_IMGS(ByVal Area As String) As System.Data.DataSet
        Dim inValue As GetSTRIKES_IMGSRequest = New GetSTRIKES_IMGSRequest()
        inValue.Area = Area
        Dim retVal As GetSTRIKES_IMGSResponse = CType(Me,IService1).GetSTRIKES_IMGS(inValue)
        Return retVal.GetSTRIKES_IMGSResult
    End Function
    
    <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Function IService1_GetSTRIKES_IMGSAsync(ByVal request As GetSTRIKES_IMGSRequest) As System.Threading.Tasks.Task(Of GetSTRIKES_IMGSResponse) Implements IService1.GetSTRIKES_IMGSAsync
        Return MyBase.Channel.GetSTRIKES_IMGSAsync(request)
    End Function
    
    Public Function GetSTRIKES_IMGSAsync(ByVal Area As String) As System.Threading.Tasks.Task(Of GetSTRIKES_IMGSResponse)
        Dim inValue As GetSTRIKES_IMGSRequest = New GetSTRIKES_IMGSRequest()
        inValue.Area = Area
        Return CType(Me,IService1).GetSTRIKES_IMGSAsync(inValue)
    End Function
End Class
