'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AHAS

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''lbl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RadioButtonList2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonList2 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''hiddenID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hiddenType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenType As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hiddenM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenM As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hiddenD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenD As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hiddenH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenH As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hiddenIP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenIP As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hiddenQuery control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenQuery As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hiddenVR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenVR As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hiddenIR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenIR As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hiddenSR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenSR As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hiddenMOA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenMOA As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hiddenAA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenAA As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hiddenRANGE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenRANGE As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hiddenMILAIR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenMILAIR As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hiddenUNIT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenUNIT As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hiddenUNIT2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenUNIT2 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hiddenICAO1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenICAO1 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hiddenICAO2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddenICAO2 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''area control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents area As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lstMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstMonth As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lstDay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstDay As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lstHour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstHour As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnShowChart.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnShowChart As Global.System.Web.UI.WebControls.Button

    Protected Label1 As Global.System.Web.UI.WebControls.Label

    Protected Chart1 As Global.System.Web.UI.DataVisualization.Charting.Chart

End Class
